version: "3.8"
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: usersandstatuses
  api:
    build:
      dockerfile: Dockerfile
      context: ./
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:5432/usersandstatuses
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"